CREATE TABLE brim_contacts (
  item_id int(11) NOT NULL auto_increment,
  owner varchar(70) NOT NULL default '',
  parent_id int(11) NOT NULL default '0',
  is_parent tinyint(1) default NULL,
  name varchar(70) NOT NULL default '',
  description text,
  visibility varchar(25) default NULL,
  category varchar(50) default NULL,
  is_deleted tinyint(1) default NULL,
  when_created datetime default NULL,
  when_modified datetime default NULL,
  alias varchar(70) default NULL,
  address varchar(255) default NULL,
  birthday datetime default NULL,
  mobile varchar(25) default NULL,
  faximile varchar(25) default NULL,
  tel_home varchar(25) default NULL,
  tel_work varchar(25) default NULL,
  organization varchar(70) default NULL,
  org_address varchar(255) default NULL,
  job varchar(70) default NULL,
  email1 varchar(70) default NULL,
  email2 varchar(70) default NULL,
  email3 varchar(70) default NULL,
  webaddress1 varchar(70) default NULL,
  webaddress2 varchar(70) default NULL,
  webaddress3 varchar(70) default NULL,
  PRIMARY KEY  (item_id),
  KEY itemId (item_id)
)
