create table brim_contacts (
	item_id serial not null,
	owner   char (70) not null,
	parent_id integer not null,
	is_parent integer default 0,
	name text not null,
	description text,
	visibility char (15),
	category char (50),
	is_deleted integer default 0,
	when_created timestamp,
	when_modified timestamp,
	alias char (70),
	address TEXT,
	birthday timestamp,
	mobile char (25),
	faximile char (25),
	tel_home char (25),
	tel_work char (25),
	organization char (70),
	org_address TEXT,
	job char (70),
	email1 char (70),
	email2 char (70),
	email3 char (70),
	webaddress1 char (70),
	webaddress2 char (70),
	webaddress3 char (70),
	primary key (item_id)
)
