<?php

/**
 * This file is part of the Brim project.
 * The brim-project is located at the following
 * location: {@link http://www.brim-project.org/ http://www.brim-project.org/}
 *
 * <pre> Enjoy :-) </pre>
 *
 * @author Barry Nauta
 * @package org.brim-project.templates
 * @subpackage barrel
 *
 * @copyright [brim-project.org] - Copyright (c) 2003 - 2005 Barry Nauta
 *
 * @license http://opensource.org/licenses/gpl-license.php
 * The GNU Public License
 */
$iconDefs = array ();

$iconDefs ['edit'] = array (
	'src'=>'framework/view/pics/edit.gif',
	'alt'=>'edit',
	'width'=>14,
	'height'=>15,
	'border'=>0
);
?>
