<?php

/**
 * This file is part of the Brim project.
 * The brim-project is located at the following
 * location: {@link http://www.brim-project.org/ http://www.brim-project.org/}
 *
 * <pre> Enjoy :-) </pre>
 *
 * @author Barry Nauta
 * @package org.brim-project.templates
 * @subpackage barrel
 *
 * @copyright [brim-project.org] - Copyright (c) 2003 - 2005 Barry Nauta
 *
 * @license http://opensource.org/licenses/gpl-license.php
 * The GNU Public License
 */
$icons = array ();
$icons['root']='<h2>Root</h2>';

$icons['up']=
	"[...up...]";

$icons['bar']=
	'<img alt="" src="framework/view/pics/tree/empty_bar.gif" border="0">';
$icons['minus']=
	'<img alt="-" src="framework/view/pics/tree/shaded_minus.gif" border="0">';
$icons['folder_open']=
	'<img alt="" src="framework/view/pics/tree/gnome_folder_open.gif" border="0" class="folder_open">';
$icons['corner']=
	'<img alt="" src="framework/view/pics/tree/empty_corner.gif" border="0">';
$icons['plus']=
	'<img alt="+" src="framework/view/pics/tree/shaded_plus.gif" border="0">';
$icons['tee']=
	'<img alt="" src="framework/view/pics/tree/empty_tee.gif" border="0">';
$icons['folder_closed']=
	'<img alt="" src="framework/view/pics/tree/gnome_folder_closed.gif" border="0" class="folder_closed">';
$icons['node']=
	'<img alt="" src="framework/view/pics/tree/shaded_item.gif" border="0">';
$icons['open_new_window']=
	'&nbsp<img alt="" src="framework/view/pics/tree/arrow.gif" border="0">';
$icons['delete']=
	'<img alt="delete" src="framework/view/pics/delete.gif" border="0">';
$icons['edit']=
	'<img alt="edit" src="framework/view/pics/edit.gif" border="0">';

$icons['message']=
	'<img alt="" src="framework/view/pics/gnome_message.gif" border="0">';
$icons['warning']=
	'<img alt="!" src="framework/view/pics/gnome_warn.gif" border="0">';

$icons['up_arrow']=
	'<img alt="" src="framework/view/pics/arrows/b_up_pointer.gif" border="0">';
$icons['down_arrow']=
	'<img alt="" src="framework/view/pics/arrows/b_down_pointer.gif" border="0">';
$icons['up_arrow_shaded']=
	'<img alt="" src="framework/view/pics/arrows/b_up_pointer_gray.gif" border="0">';
$icons['down_arrow_shaded']=
	'<img alt="" src="framework/view/pics/arrows/b_down_pointer_gray.gif" border="0">';
$icons['locked']=
	'<img src="framework/view/pics/locked.gif" alt="locked" border="0">';
$icons['unlocked']=
	'<img src="framework/view/pics/unlocked.gif" alt="unlocked" border="0">';
$icons['overviewexpand']=
	'<img src="framework/view/pics/tree/book-closed.gif" border="0" alt="expand">';
$icons['overviewcollapse']=
	'<img src="framework/view/pics/tree/book-open.gif" border="0" alt="collapse">';
$icons['busy']=
	'<img src="framework/view/pics/loading/spinner.gif" border="0" alt="busy">';
	
$icons['refresh']='<img src="framework/view/pics/refresh.png" border="0" alt="refresh">';

$icons['fullTrash']="templates/barrel/pics/trashcan_full.png";
$icons['emptyTrash']="templates/barrel/pics/trashcan_empty.png";
$icons['completedTasks']="templates/barrel/plugins/pics/tasks/completedTasks.png";
$icons['uncompletedTasks']="templates/barrel/plugins/pics/tasks/uncompletedTasks.png";

$icons['closedFolder']=array (
        'location'=>'framework/view/pics/tree/gnome_folder_closed.gif',
        'width'=>'18',
        'height'=>'18',
        'alt'=>'Folder');
$icons['openFolder']=array (
        'location'=>'framework/view/pics/tree/gnome_folder_open.gif',
        'width'=>'18',
        'height'=>'18',
        'alt'=>'Folder');
$icons['item']=array (
        'location'=>'framework/view/pics/tree/shaded_item.gif',
        'width'=>'16',
        'height'=>'16',
        'alt'=>'Item');

?>
