<?php

/**
 * This file is part of the Brim project.
 * The brim-project is located at the following
 * location: {@link http://www.brim-project.org/ http://www.brim-project.org/}
 *
 * <pre> Enjoy :-) </pre>
 *
 * @author Barry Nauta
 * @package org.brim-project.templates
 * @subpackage barry
 *
 * @copyright [brim-project.org] - Copyright (c) 2003 - 2005 Barry Nauta
 *
 * @license http://opensource.org/licenses/gpl-license.php
 * The GNU Public License
 */
$icons = array ();
$icons['root']='<h2>RooT</h2>';

$icons['up']=
	"[...up...]";

$icons['bar']=
	'<img src="framework/view/pics/tree/empty_bar.gif" border="0">';
$icons['minus']=
	'<img src="framework/view/pics/tree/shaded_minus.gif" border="0">';
$icons['folder_open']=
	'<img src="framework/view/pics/tree/gnome_folder_open.gif" border="0">';
$icons['corner']=
	'<img src="framework/view/pics/tree/empty_corner.gif" border="0">';
$icons['plus']=
	'<img src="framework/view/pics/tree/shaded_plus.gif" border="0">';
$icons['tee']=
	'<img src="framework/view/pics/tree/empty_tee.gif" border="0">';
$icons['folder_closed']=
	'<img src="framework/view/pics/tree/gnome_folder_closed.gif" border="0">';
$icons['node']=
	'<img src="framework/view/pics/tree/oerdec_item.gif" border="0">';
$icons['open_new_window']=
	'&nbsp<img src="framework/view/pics/tree/arrow.gif" border="0">';
$icons['delete']=
	'<img src="framework/view/pics/delete.gif" border="0">';
$icons['edit']=
	'<img src="framework/view/pics/edit.gif" border="0">';


$icons['message']=
	'<img src="framework/view/pics/gnome_message.gif" border="0">';
$icons['warning']=
	'<img src="framework/view/pics/gnome_warn.gif" border="0">';
$icons['up_arrow']=
	'<img src="framework/view/pics/arrows/b_up_pointer.gif" border="0">';
$icons['down_arrow']=
	'<img src="framework/view/pics/arrows/b_down_pointer.gif" border="0">';
$icons['up_arrow_shaded']=
	'<img src="framework/view/pics/arrows/b_up_pointer_gray.gif" border="0">';
$icons['down_arrow_shaded']=
	'<img src="framework/view/pics/arrows/b_down_pointer_gray.gif" border="0">';
$icons['locked']=
	'<img src="framework/view/pics/locked.gif" alt="locked" border="0">';
$icons['unlocked']=
	'<img src="framework/view/pics/unlocked.gif" alt="unlocked" border="0">';
$icons['overviewexpand']=
	'<img src="framework/view/pics/tree/book-closed.gif" border="0" alt="expand">';
$icons['overviewcollapse']=
	'<img src="framework/view/pics/tree/book-open.gif" border="0" alt="expand">';
$icons['busy']=
	'<img src="framework/view/pics/loading/spinner.gif" border="0" alt="busy">';
$icons['refresh']='<img src="framework/view/pics/refresh_icon.gif" border="0" alt="refresh">';

?>