<?php 
define ('SETTINGS_SETTINGS','Settings');
define ('SETTINGS_WARNING_CANNOT_WRITE_TO_CONFIGURATION_FILE','WARNING: Cannot write to configuration file ');
define ('SETTINGS_NOTICE_CONFIGINC_WORLD_WRITABLE','Saved. Please ensure that the configuration file config.inc.php is not world-writable now.');
define ('SETTINGS_SITE','Site');
define ('SETTINGS_MAIL','Mail');
define ('SETTINGS_SITE_NAME','Site Name');
define ('SETTINGS_SITE_URL','Site URL');
define ('SETTINGS_EMAIL','E-mail');
define ('SETTINGS_BASE_PATH','Base Path');
define ('SETTINGS_ADMIN_LOGIN_VALID_FOR','Admin Login Time');
define ('SETTINGS_DEFAULT_TEMPLATE','Default Template');
define ('SETTINGS_DEFAULT_USER_CLASS','Default User Class');
define ('SETTINGS_DEFAULT_ADMIN_GROUP','Default Admin Group');
define ('SETTINGS_DATABASE','Database');
define ('SETTINGS_HTTPS','Secure (HTTPS) URL');
define ('SETTINGS_USERS_DEFAULTS','User Class Settings');
define ('SETTINGS_FROM','Default Mail Sender');
define ('SETTINGS_SEO_DEFAULT','SEO Default');
define ('SETTINGS_SSL','SSL');
define ('SETTINGS_HOST','Host');
define ('SETTINGS_META_KEY','Default Meta Keywords');
define ('SETTINGS_META_DESCRIPTION','Default Meta Description');
define ('SETTINGS_ENABLED','Enabled');
define ('SETTINGS_NO_TEMPLATES_FOUND','No Templates Found');
define ('SETTINGS_ENABLE_SEO','Enable search engine friendly URL');
define ('SETTINGS_SETTINGS','Settings');
define ('SETTINGS_ERROR_CANNOT_WRITE','WARNING: Cannot write to configuration file ');
define ('SETTINGS_WINDIR','WINDIR');
define ('SETTINGS_ERROR_CANNOT_SAVE',"Cannot save to configuration file");
define ('SETTINGS_SQL_CACHE_TIME','SQL Cache Time (in seconds)');
define ('SETTINGS_ENABLE_SQL_CACHE','Enable SQL Cache');
define ('SETTINGS_ENFORCE_SQL_ROW_LIMIT','Enforce SQL row limit');
define ('SETTINGS_FORCE_SSL_ADMIN_LOGIN','Force SSL login to the backend (Administration)');
?>