
																				<?php
			
																					# File generated by DBHcms 1582548114

																					$cfg['blowfish_secret'] = 'n9en9yq0kkw1d23y';

																					$cfg['Servers'][1]['auth_type'] = 'cookie';

																					$cfg['Servers'][1]['host'] = 'localhost';
																					$cfg['Servers'][1]['connect_type'] = 'tcp';
																					$cfg['Servers'][1]['compress'] = false;
																					$cfg['Servers'][1]['extension'] = 'mysql';

																					$cfg['Servers'][1]['only_db'] = 'DBcontent';

																				?> 